name: 'Saplings - Full HTML Editor'
description: 'Configures a rich CKEditor experience.'
type: 'Site'
install:
  # Core.
  - ckeditor5
  - editor
  - node
  - media
  - media_library
  # Contrib.
  - ckeditor5_plugin_pack
  - ckeditor5_plugin_pack_indent_block
  - ckeditor_bs_grid
  - editor_advanced_link
  - linkit
  - responsive_tables_filter
config:
  strict: false
  import:
    linkit: '*'
